language: java

jdk:
  - openjdk8

services:
  - docker

before_install:
  - echo "$CONFIG_FILE" | base64 -d >> config.properties
  - mkdir certificates
  - echo "$KEYSTORE" | base64 -d > certificates/kafka.client.keystore.jks
  - echo "$TRUSTSTORE" | base64 -d > certificates/kafka.client.truststore.jks

matrix:
  include:
  - name: "Test java"
    install: 
      - cd producer && ./gradlew assemble
      - docker-compose build mongodb
      - docker-compose up -d mongodb
      - sleep 5
    script: ./gradlew check
  - name: "Test python"
    language: python
    python: "3.5"
    install: 
      - cd analyzer && pip3 install -r requirements.txt
      - docker-compose build mongodb
      - docker-compose up -d mongodb
      - sleep 5
    script: pytest
  - name: "Test docker-build"
    script: docker-compose build
    

notifications:
  slack:
    secure: 2fvJmnos9G4JMD8lAGT+MdwBScku1WQ5NMqDBwzrXq1UbpkeX8Ds3aahBsRlXbS79Hz7JQDPT8/ui1UN+w5ielBCiOQrdY4YLQt88ljU6ghgunTvlZ1BR2m0xyIaDshnT6CX27SzlTzuXiQuk+cPWvBw/qg1y6cjUyqhzzNHuhJuQWFktCAtL2jpk/Vo154wdwRqmIXyEolSdk4ObclKWeX+LIfF8r0+mECsUIKtiYkFXZ+Zvek0JeHqs7vqLn71FPrbgpBvwA5nBz3Mvau2zM+YW5DeYNKX72KL6dgSbKm8hWxXlRqD+jEQhWhp8VUmbeedOFwHwrrIl9oXavULyLji+A5BRDCmQP2SJBxe4nHYkMdTczH2cXKKv+fbTYOm5YhvDFuIvro61vB9gEPagt5/nJPa8nXZM5WynJ3Ttb3BR7zZPIGaowbZuA8HIus3bZnsWLbkg+Ath4dNDRMqsqduyviDzWflQHKz2Z0QdISmZb57yp2OvEtjCKKp7UnuL1R5+MrX794/sCLnf7puVc4ikeZRE3679E2oL2EjYvwgLVCtA0ykrC9YF3pCZlXKs4MxgvIO7w+2n9sQDaJVi45fbyWEur6MOvPDgxYOUXJQAdeAdQRPaE3yyeXyZTQ8uObx3K+8MHnxeUSSM9GteBENs86AeQ1YCdqrCSXjAA0=
