version: '2'
services:
  producer:
    build: ./producer
    image: producer
    depends_on:
      - start_dependencies
    volumes:
      - ./config.properties:/usr/local/config.properties
      - ./certificates:/usr/local/certificates
    ports:
    - "8080:8080"
  analyzer:
    build: ./analyzer
    image: analyzer
    depends_on:
      - start_dependencies
    volumes:
      - ./config.properties:/config.properties
      - ./certificates:/certificates
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "tweets:1:1,test-tweets:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongodb:
    build: ./mongodb
    ports:
      - "27017:27017" 
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - kafka
      - mongodb
    command: kafka:9092 mongodb:27017